#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "leafwiki"
name = "LeafWiki"
description.en = "Wiki with markdown stored on disk"
description.fr = "Wiki avec markdown stockés sur disque"

version = "0.14.1~ynh1"

maintainers = ["DeMiro5001"]

[upstream]
license = "MIT"
website = "https://leafwiki.com/"
demo = "https://demo.leafwiki.com/home"
code = "https://github.com/perber/leafwiki"

[integration]
yunohost = ">= 12.1.40"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = true

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/leafwiki"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "Admin password."
    help.fr = "Mot de passe admin."
    type = "password"

    [install.leafwiki_public_access]
    ask.en = "Enable public access"
    help.fr = "Activer l'accès public"
    type = "boolean"
    default = true

[resources]
    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    extract = false
    rename = "leafwiki"
    amd64.url = "https://github.com/perber/leafwiki/releases/download/v0.14.1/leafwiki-v0.14.1-linux-amd64"
    amd64.sha256 = "331c11f671ea7e4097e7d3f30ff9e185f663dc7c6863879964ed155ec680816a"
    arm64.url = "https://github.com/perber/leafwiki/releases/download/v0.14.1/leafwiki-v0.14.1-linux-arm64"
    arm64.sha256 = "48c265f543573efc073e139f0847ad704368836b6890d095f4660d42aa14ab6e"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "leafwiki-v\\d+\\.\\d+\\.\\d+\\-linux-amd64$"
    autoupdate.asset.arm64 = "leafwiki-v\\d+\\.\\d+\\.\\d+\\-linux-arm64$"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
